### ISSUE TITLE
Fatal error with wp-cli

### ISSUE THREAD

**Issue by 0x6d617474** [moderntribe/events-gutenberg#192]
The `wp-cli` tool fails to run commands for any site where the base events calendar plugin is activated along with this gutenberg extension plugin. The following fatal error occurs when attempting to run any commands: 

```
PHP Notice:  Undefined index: __tribe_events_gutenberg_plugin in /srv/http/wordpress/wp-content/plugins/events-gutenberg/src/Tribe/Provider.php on line 12
PHP Stack trace:
PHP   1. {main}() /usr/bin/wp:0
PHP   2. include() /usr/bin/wp:4
PHP   3. include() phar:///usr/bin/wp/php/boot-phar.php:8
PHP   4. WP_CLI\bootstrap() phar:///usr/bin/wp/php/wp-cli.php:23
PHP   5. WP_CLI\Bootstrap\LaunchRunner->process() phar:///usr/bin/wp/php/bootstrap.php:75
PHP   6. WP_CLI\Runner->start() phar:///usr/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php:23
PHP   7. WP_CLI\Runner->load_wordpress() phar:///usr/bin/wp/php/WP_CLI/Runner.php:1107
PHP   8. require() phar:///usr/bin/wp/php/WP_CLI/Runner.php:1182
PHP   9. do_action() /srv/http/wordpress/wp-settings.php:327
PHP  10. WP_Hook->do_action() /srv/http/wordpress/wp-includes/plugin.php:453
PHP  11. WP_Hook->apply_filters() /srv/http/wordpress/wp-includes/class-wp-hook.php:310
PHP  12. Tribe__Events_Gutenberg__Plugin->load() /srv/http/wordpress/wp-includes/class-wp-hook.php:286
PHP  13. tribe_register_provider() /srv/http/wordpress/wp-content/plugins/events-gutenberg/events-gutenberg.php:69
PHP  14. Tribe__Container->register() /srv/http/wordpress/wp-content/plugins/the-events-calendar/common/src/Tribe/Container.php:242
PHP  15. Tribe__Events_Gutenberg__Provider->register() /srv/http/wordpress/wp-content/plugins/the-events-calendar/common/vendor/lucatume/di52/src/tad/DI52/Container.php:476
PHP Fatal error:  Uncaught RuntimeException:   'gutenberg.assets'
     =>  Error while making  'gutenberg': 'gutenberg' is not a bound alias or an existing class. in /srv/http/wordpress/wp-content/plugins/the-events-calendar/common/vendor/lucatume/di52/src/tad/DI52/Container.php:348
Stack trace:
#0 /srv/http/wordpress/wp-content/plugins/the-events-calendar/common/vendor/lucatume/di52/src/tad/DI52/Container.php(281): tad_DI52_Container->resolve('gutenberg.asset...')
#1 /srv/http/wordpress/wp-content/plugins/the-events-calendar/common/src/Tribe/Container.php(176): tad_DI52_Container->make('gutenberg.asset...')
#2 /srv/http/wordpress/wp-content/plugins/events-gutenberg/events-gutenberg.php(73): tribe('gutenberg.asset...')
#3 /srv/http/wordpress/wp-includes/class-wp-hook.php(286): Tribe__Events_Gutenberg__Plugin->load('')
#4 /srv/http/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /srv/http/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /srv/http/wordpress/wp-settings.php(327): do_action('plugins_loaded')
# in /srv/http/wordpress/wp-content/plugins/the-events-calendar/common/vendor/lucatume/di52/src/tad/DI52/Container.php on line 348
```

This error means that no `wp-cli` commands can be run against any site running the plugin, which breaks a lot of automation.  

The plugin is working normally when accessed through the web interface, and doesn't seem to throw any errors.  

This issue occurs both for the latest zip file under Releases, and when building the plugin from source.

I believe the first notice is due to the `unset($GLOBALS['__tribe_events_gutenberg_plugin'])` being called while the `$__tribe_events_gutenberg_plugin` is still being written to, but it shouldn't be related to the fatal error that is causing problems.  

**Steps to Reproduce:**  
1. Install the `wp-cli` tool  
2. Install a fresh copy of wordpress  
3. Install both `the-events-calendar` and `events-gutenberg`  
4. Note that the `wp-cli` tool works fine before activating  
5. Activate both plugins  
6. Attempt to run any `wp-cli` command and note the error

**Comment by bordoni** [comment]
Thanks for the report @0x6d617474, that is definitely a bug we need to solve on our side.

We will make sure to include that on our next release.

**Comment by 0x6d617474** [comment]
Simply running the `wp` command to get the help text resulted in the error for me. Any other command results in the same error (I was specifically using `wp plugin list` when I first noticed it)

**Comment by mitogh** [comment]
Thanks @0x6d617474 will look into this with this information.
