### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function register_block_type()

### ISSUE THREAD

**Issue by chronicole** [moderntribe/events-gutenberg#6]
I had TEC (`bucket/gutenberg`, `32d735a` with `common` at `2c5b159`), Gutenberg (`master`, `3fc70e7198c86cf007ee93e4287a457357b9a31e`), Events Gutenberg (`master`, `66c7d836f585738b065b3caf1239394138be25bf`) and Debug Bar installed and active on WP 4.9.4 and got the following error

```
Fatal error: Uncaught Error: Call to undefined function register_block_type() in /Users/chronicole/code/tribe-guten/wp-content/plugins/events-gutenberg/src/Tribe/Blocks/Abstract.php:51 Stack trace: #0 /Users/chronicole/code/tribe-guten/wp-content/plugins/the-events-calendar/common/vendor/lucatume/di52/src/tad/DI52/closuresSupport.php(24): Tribe__Events_Gutenberg__Blocks__Abstract->register('') #1 /Users/chronicole/code/tribe-guten/wp-includes/class-wp-hook.php(286): {closure}('') #2 /Users/chronicole/code/tribe-guten/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 /Users/chronicole/code/tribe-guten/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /Users/chronicole/code/tribe-guten/wp-content/plugins/events-gutenberg/src/Tribe/Editor.php(112): do_action('tribe_events_ed...') #5 /Users/chronicole/code/tribe-guten/wp-content/plugins/the-events-calendar/common/vendor/lucatume/di52/src/tad/DI52/closuresSupport.php(24): Tribe__Events_Gutenberg__Editor->register_blocks('') #6 /Users/chronicole/c in /Users/chronicole/code/tribe-guten/wp-content/plugins/events-gutenberg/src/Tribe/Blocks/Abstract.php on line 51
```

I did troubleshoot this with @bordoni in Slack and I'd forgot the `yarn install`/`yarn build dev` piece for Gutenberg and EG, but noting this error for future reference.

**Comment by bordoni** [comment]
This is fixed, back to QA.

**Comment by bordoni** [comment]
Tested this multiple times, closing.
